In [1]:
import torch
from torch.nn import Conv2d
from torch.autograd import Variable
import numpy as np

In [2]:
# np.concatenate?
Conv2d?

In [3]:
X_np_1 = np.array([
    [-1, -2, -3],
    [4, 5, 6],
    [7, 8, 9]])
X_np_1 = X_np_1.reshape(1, 1, X_np_1.shape[0], X_np_1.shape[1])

In [4]:
X_np_2 = np.array([
    [1, 2, 3],
    [-4, -5, -6],
    [7, 8, 9]])
X_np_2 = X_np_2.reshape(1, 1, X_np_2.shape[0], X_np_2.shape[1])

In [5]:
X_np_3 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [-7, -8, -9]])
X_np_3 = X_np_3.reshape(1, 1, X_np_3.shape[0], X_np_3.shape[0])

In [6]:
# X_np = np.concatenate((X_np_1, X_np_2, X_np_3), axis=1)
X_np = X_np_1

In [7]:
X_np.shape

(1, 1, 3, 3)

In [8]:
# conv1 = Conv2d(in_channels=X_np.shape[1], out_channels=2, kernel_size=2)
conv1 = Conv2d(in_channels=X_np.shape[1], out_channels=1, kernel_size=2)

In [9]:
X_tensor = torch.FloatTensor(X_np)

In [10]:
X_var = Variable(X_tensor)

In [11]:
conv1.weight

Parameter containing:
(0 ,0 ,.,.) = 
  0.2686 -0.4987
 -0.0355 -0.0495
[torch.FloatTensor of size 1x1x2x2]

In [22]:
conv1.bias

Parameter containing:
1.00000e-02 *
 -4.2910
[torch.FloatTensor of size 1]

In [13]:
y_var = conv1(X_var)

In [14]:
y_var

Variable containing:
(0 ,0 ,.,.) = 
  0.2963  0.4414
 -2.1066 -2.4217
[torch.FloatTensor of size 1x1x2x2]

In [24]:
bias_0_np = conv1.bias[0].data.numpy()
bias_0_np

array([-0.04291008], dtype=float32)

In [15]:
conv1_weight_0 = conv1.weight[0, :, :, :]

In [16]:
conv1_weight_0_np = conv1_weight_0.data.numpy()

In [17]:
conv1_weight_0_np

array([[[ 0.26856387, -0.49866667],
        [-0.03554581, -0.04946886]]], dtype=float32)

In [18]:
X_np

array([[[[-1, -2, -3],
         [ 4,  5,  6],
         [ 7,  8,  9]]]])

In [25]:
# np.sum(np.multiply(X_np_1[0, 0, :2, :2], conv1_weight_0_np[0, :, :])
# + np.multiply(X_np_2[0, 0, :2, :2], conv1_weight_0_np[1, :, :])
# + np.multiply(X_np_3[0, 0, :2, :2], conv1_weight_0_np[2, :, :]))
np.sum(np.multiply(X_np[0, 0, :2, :2], conv1_weight_0_np[0, :, :]))+bias_0_np

array([ 0.29633188], dtype=float32)