In [1]:
from mxnet import nd
import numpy as np

/home/cgf/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


# 创建NDArray

In [2]:
x = nd.arange(10)

In [3]:
x
# 其中打印出来的NDArray 10 @cpu(0)表示长度为10的一维数组，且被创建在CPU主内存上，CPU里面的0没有特别的意义。


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
<NDArray 10 @cpu(0)>

In [4]:
x.shape

(10L,)

In [5]:
x.size

10L

In [6]:
x = x.reshape((2, 5))

In [7]:
x


[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
<NDArray 2x5 @cpu(0)>

In [8]:
nd.zeros((2, 2))


[[0. 0.]
 [0. 0.]]
<NDArray 2x2 @cpu(0)>

In [9]:
nd.ones((2, 2))


[[1. 1.]
 [1. 1.]]
<NDArray 2x2 @cpu(0)>

In [10]:
y = nd.array([[1, 2], [3, 4], [5, 6]])

In [11]:
y.shape

(3L, 2L)

In [12]:
nd.random.normal(loc=0, scale=1, shape=(3, 4)) # 随机生成NDArray中每一个元素的值，该函数采样于均值为0，标注差为1的正态分布


[[ 2.2122064   0.7740038   1.0434405   1.1839255 ]
 [ 1.8917114  -1.2347414  -1.771029   -0.45138445]
 [ 0.57938355 -1.856082   -1.9768796  -0.20801921]]
<NDArray 3x4 @cpu(0)>

# 运算

In [13]:
x = nd.random.normal(loc=0, scale=1, shape=(3, 4))
y = nd.random.normal(loc=0, scale=1, shape=(3, 4))

In [14]:
x


[[ 0.2444218  -0.03716067 -0.48774993 -0.02261727]
 [ 0.57461417  1.4661262   0.6862904   0.35496104]
 [ 1.0731696   0.12017461 -0.9711102  -0.77569664]]
<NDArray 3x4 @cpu(0)>

In [15]:
y


[[-0.7882176   0.7417728  -1.4734439  -1.0730928 ]
 [-1.0424827  -1.3278849  -1.4749662  -0.52414197]
 [ 1.2662556   0.8950642  -0.6015945   1.2040559 ]]
<NDArray 3x4 @cpu(0)>

In [16]:
x+y


[[-0.5437958   0.7046121  -1.9611938  -1.09571   ]
 [-0.46786857  0.13824129 -0.7886758  -0.16918093]
 [ 2.339425    1.0152388  -1.5727048   0.42835927]]
<NDArray 3x4 @cpu(0)>

In [17]:
x*y


[[-0.19265756 -0.02756477  0.71867216  0.02427043]
 [-0.59902537 -1.9468468  -1.0122551  -0.18604998]
 [ 1.358907    0.10756399  0.58421457 -0.93398213]]
<NDArray 3x4 @cpu(0)>

In [18]:
x/y


[[-0.3100943  -0.0500971   0.33102715  0.02107671]
 [-0.55119777 -1.1041064  -0.46529227 -0.6772231 ]
 [ 0.84751415  0.13426368  1.6142272  -0.6442364 ]]
<NDArray 3x4 @cpu(0)>

In [19]:
y.exp()


[[0.45465446 2.0996544  0.22913502 0.34194928]
 [0.35257822 0.26503724 0.22878647 0.5920631 ]
 [3.5475442  2.4474928  0.5479373  3.3336103 ]]
<NDArray 3x4 @cpu(0)>

In [20]:
nd.dot(x, y.T)


[[ 0.5227202  0.5258089  0.5424345]
 [-0.757505  -3.7441773  2.05441  ]
 [ 1.5065219  0.560591   1.1167035]]
<NDArray 3x3 @cpu(0)>

# NDArray和NumPy相互转换

In [21]:
p = np.ones((2, 3))
d = nd.array(p)

In [22]:
d


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [23]:
d.asnumpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

# 小结

NDArray 是MXNet中存储和变换数据的主要工具。
我们可以轻松地对NDArray进行创建、运算、指定索引和与NumPy之间的相互变换。

# 自动求梯度

对函数$y=2x^Tx$关于列向量x的梯度

In [24]:
from mxnet import autograd, nd

In [25]:
x = nd.arange(4).reshape((4, 1))

In [26]:
x


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>

为了求取有关变量x的梯度，需要先调用attach_grad函数来申请梯度所需要的内存。

In [27]:
x.attach_grad() # 为了求取有关变量x的梯度首先通过attach_grad函数来申请梯度所需要的内存

In [28]:
# 使用record函数来要求MXNet记录求梯度有关的计算
with autograd.record():
    y = 2*nd.dot(x.T, x)

In [29]:
# y最后是一个标量，通过y.backward反向传播来自动求取梯度，如果y不是一个标量，MXNet将默认先将y中元素求和得到新的变量，再求该变量有关x的梯度
y.backward() # 根据数学推到，最后的结果应该是4x

In [30]:
x.grad, x.grad==4*x

(
 [[ 0.]
  [ 4.]
  [ 8.]
  [12.]]
 <NDArray 4x1 @cpu(0)>, 
 [[1.]
  [1.]
  [1.]
  [1.]]
 <NDArray 4x1 @cpu(0)>)

In [31]:
# nd.Convolution?