In [1]:
import scipy
from scipy import linalg
import numpy as np

In [2]:
# linalg.svd?

In [3]:
a = np.random.randn(9, 6) + 1.j*np.random.randn(9, 6)

In [4]:
U, s, Vh = linalg.svd(a)

In [5]:
M = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 4, 0, 0, 0]])

In [6]:
U, s, Vh = linalg.svd(M)

In [7]:
U

array([[ 0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  0., -1.],
       [ 1.,  0.,  0.,  0.]])

In [8]:
s

array([ 4.        ,  3.        ,  2.23606798,  0.        ])

In [9]:
Vh

array([[-0.        ,  1.        ,  0.        , -0.        ,  0.        ],
       [-0.        ,  0.        ,  1.        , -0.        ,  0.        ],
       [ 0.4472136 ,  0.        ,  0.        ,  0.        ,  0.89442719],
       [ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ],
       [-0.89442719,  0.        ,  0.        ,  0.        ,  0.4472136 ]])